FROM ubuntu:14.04
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		build-essential \
		cmake \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		git \
		pv \
	&& apt-get clean \
	&& rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN useradd -m dev \
	&& adduser dev sudo \
	&& echo "%sudo ALL=NOPASSWD: ALL" >> /etc/sudoers

CMD ["/bin/su", "-", "dev"]
