FROM centos:7
RUN	yum install -y \
		gcc-c++ \
		make \
		sudo \
		cmake \
	&& yum clean all
# epel-release is required for pv (pipe viewer)
RUN	yum install -y epel-release \
	&& yum install -y \
		git \
		pv \
	&& yum clean all
RUN	useradd -m -G wheel dev \
	&& echo "%wheel ALL=NOPASSWD: ALL" >> /etc/sudoers

CMD ["/bin/su", "-", "dev"]
